Feature/order entity
thebaker10/Fresh-Mart pull request #30
Opened 2022-11-06 21:44 UTC by thebaker10

2022-11-07 00:11 UTC, noko12312 requested changes

2022-11-07 00:11 UTC, noko12312 commented on docker/api/src/Domain/Order/User_order.php
> +
```suggestion

    public function setUser(User $user): void{
        $this->user = $user;
    }
```

2022-11-07 00:11 UTC, noko12312 commented on docker/api/src/Domain/Order/User_order.php
> +
needs function to set user

2022-11-07 00:11 UTC, noko12312 commented on docker/api/src/Domain/Order/User_order.php
> +#[Entity, Table(name: 'user_order')]
```suggestion
#[Entity, Table(name: 'order')]
```

2022-11-07 00:11 UTC, noko12312 commented on docker/api/src/Domain/Order/User_order.php
> +#[Entity, Table(name: 'user_order')]
It is more simple to just use order for table name. The class name User_order and file name User_order.php should probably be switched to just Order as well

2022-11-07 00:11 UTC, noko12312 commented on docker/api/src/Application/Actions/Order/OrderPostAction.php
> +        $order->setProduct($user);
```suggestion
        $order->setUser($user);
```

2022-11-07 00:11 UTC, noko12312 commented on docker/api/src/Application/Actions/Order/OrderPostAction.php
> +        $order->setProduct($user);
Calls setUser function instead of setProduct

2022-11-12 00:49 UTC, thebaker10 commented
all changes requested added

2022-11-12 00:53 UTC, noko12312 approved these changes

2022-11-12 14:03 UTC, merged