Feature/search
thebaker10/Fresh-Mart pull request #52
Opened 2022-12-04 03:31 UTC by thebaker10

2022-12-04 03:58 UTC, thebaker10 commented on docker/search/src/Database.ts
> +        con.query(sql, (error, rows, fields) => {
fixed in next commit

2022-12-04 17:36 UTC, noko12312 requested changes

2022-12-04 17:36 UTC, noko12312 commented on src/Pages/ProductPage.tsx
>          <div className="bg-lightGray">
```suggestion
        <div className="bg-lightGray pt-16">
```

2022-12-04 17:36 UTC, noko12312 commented on src/Pages/ProductPage.tsx
>          <div className="bg-lightGray">
The fixed nav bar cuts off part of the product page image and product name. Adding some padding here fixes it.

2022-12-05 00:40 UTC, noko12312 approved these changes

2022-12-09 03:44 UTC, flierc-csp approved these changes

2022-12-09 04:34 UTC, merged