fixed remove issue in check out page
thebaker10/Fresh-Mart pull request #53
Opened 2022-12-04 23:52 UTC by thebaker10

2022-12-05 00:36 UTC, flierc-csp approved these changes

2022-12-05 00:38 UTC, noko12312 requested changes

2022-12-05 00:38 UTC, noko12312 commented on src/Pages/CheckOutPage.tsx
> +        setCartData([...cartData])
```suggestion
        setCartData([...cartData])
        let price = cartData[index].quantity * cartData[index].product.product_price;
        setCartTotal(cartTotal - price);
```

2022-12-05 00:38 UTC, noko12312 commented on src/Pages/CheckOutPage.tsx
> +        setCartData([...cartData])
Great job finding out how to update this on delete. When testing the only thing I noticed was that the price is not updating on deletion. Adding these two lines made the price update as well.

2022-12-09 03:42 UTC, flierc-csp approved these changes

2022-12-12 00:27 UTC, merged